In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as sk

In [2]:
read_file = pd.read_csv('C:\\Users\\ACER\\Downloads\\train.csv')

In [3]:
read_file.head()

,S/N,Gender,Age,Location,famsize,Pstatus,Medu,Fedu,traveltime,studytime,...,paid,activities,nursery,higher,internet,famrel,freetime,health,absences,Scores
0,AB1,F,13,U,GT3,A,4,4,2,2,...,no,no,yes,yes,no,4,3,3,6,17
1,AB2,F,12,U,GT3,T,1,1,1,2,...,no,no,no,yes,yes,5,3,3,4,16
2,AB3,F,10,U,LE3,T,1,1,1,2,...,yes,no,yes,yes,yes,4,3,3,10,25
3,AB4,F,10,U,GT3,T,4,2,1,3,...,yes,yes,yes,yes,yes,3,2,5,2,44
4,AB5,F,11,U,GT3,T,3,3,1,2,...,yes,no,yes,yes,no,4,3,5,4,26

In [6]:
print (read_file.keys())
print (len(read_file.keys()))

Index(['S/N', 'Gender ', 'Age', 'Location ', 'famsize', 'Pstatus', 'Medu',
       'Fedu', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup',
       'paid', 'activities', 'nursery', 'higher', 'internet', 'famrel',
       'freetime', 'health', 'absences', 'Scores'],
      dtype='object')
23

In [12]:
# using all the column we have
# logistic regression


from sklearn.model_selection import train_test_split

help(train_test_split)

Help on function train_test_split in module sklearn.model_selection._split:

train_test_split(*arrays, **options)
    Split arrays or matrices into random train and test subsets

    Quick utility that wraps input validation and
    ``next(ShuffleSplit().split(X, y))`` and application to input data
    into a single call for splitting (and optionally subsampling) data in a
    oneliner.

    Read more in the :ref:`User Guide <cross_validation>`.

    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.

    test_size : float, int, or None (default is None)
        If float, should be between 0.0 and 1.0 and represent the
        proportion of the dataset to include in the test split. If
        int, represents the absolute number of test samples. If None,
        the value is automatically set to the complement of the train size.
        If train size is also None, test size is set to 0.25.

    train_size : float, int, or None (default is None)
        If float, should be between 0.0 and 1.0 and represent the
        proportion of the dataset to include in the train split. If
        int, represents the absolute number of train samples. If None,
        the value is automatically set to the complement of the test size.

    random_state : int or RandomState
        Pseudo-random number generator state used for random sampling.

    stratify : array-like or None (default is None)
        If not None, data is split in a stratified fashion, using this as
        the class labels.

    Returns
    -------
    splitting : list, length=2 * len(arrays)
        List containing train-test split of inputs.

        .. versionadded:: 0.16
            If the input is sparse, the output will be a
            ``scipy.sparse.csr_matrix``. Else, output type is the same as the
            input type.

    Examples
    --------
    >>> import numpy as np
    >>> from sklearn.model_selection import train_test_split
    >>> X, y = np.arange(10).reshape((5, 2)), range(5)
    >>> X
    array([[0, 1],
           [2, 3],
           [4, 5],
           [6, 7],
           [8, 9]])
    >>> list(y)
    [0, 1, 2, 3, 4]

    >>> X_train, X_test, y_train, y_test = train_test_split(
    ...     X, y, test_size=0.33, random_state=42)
    ...
    >>> X_train
    array([[4, 5],
           [0, 1],
           [6, 7]])
    >>> y_train
    [2, 0, 3]
    >>> X_test
    array([[2, 3],
           [8, 9]])
    >>> y_test
    [1, 4]

In [52]:
read_file['Gender '][read_file['Gender ']== 'F'] = 0
read_file['Gender '][read_file['Gender '] == 'M'] = 1
file_new = read_file.head(50)

C:\Users\ACER\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\ACER\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(file_new,file_new['Scores'], random_state = 0)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)

In [105]:
#knn.fit(X_train, Y_train)
print (file_new.head())

#file_new['Gender '][file_new['Gender ']== 'F'] = 0
#file_new['Gender '][file_new['Gender '] == 'M'] = 1

# setting urban to 0 and rural to 2
#file_new['Location '][file_new['Location ']== 'U'] = 0
#file_new['Location '][file_new['Location ']== 'R'] = 1

# setting the famsize 
#file_new['famsize'][file_new['famsize'] == 'LE3'] = 0 # less than 3
#file_new['famsize'][file_new['famsize'] == 'GT3'] = 1 # greater than 3

# Pstatus
#file_new['Pstatus'][file_new['Pstatus'] == 'T'] = 1 # living together
#file_new['Pstatus'][file_new['Pstatus'] == 'A'] = 0 # living Apart

# paid
#file_new['paid'][file_new['paid'] == 'yes'] = 1 # yes
#file_new['paid'][file_new['paid'] == 'no'] = 0 # no

# activities
#file_new['activities'][file_new['activities'] == 'yes'] = 1 # yes
#file_new['activities'][file_new['activities'] == 'no'] = 0 # no

# nursery
#file_new['nursery'][file_new['nursery'] == 'yes'] = 0 # yes
#file_new['nursery'][file_new['nursery'] == 'no'] = 1 # no

# higher
#file_new['higher'][file_new['higher'] == 'yes'] = 0 # yes
#file_new['higher'][file_new['higher'] == 'no'] = 1 # no

#def replace(x):
#    file_new[x][file_new[x] == 'yes'] = 0 # yes
#    file_new[x][file_new[x] == 'no'] = 1 # no
#replace('paid')
#print (file_new['paid'])

# s/n
def file():
    count = 1
    for i in file_new['S/N']:
        file_new['S/N'].replace(i, count)
        count += 1
    return file_new["S/N"]

   S/N Gender   Age Location  famsize Pstatus  Medu  Fedu  traveltime  \
0  AB1       0   13         0       1       1     4     4           2
1  AB2       0   12         0       1       0     1     1           1
2  AB3       0   10         0       0       0     1     1           1
3  AB4       0   10         0       1       0     4     2           1
4  AB5       0   11         0       1       0     3     3           1

   studytime   ...    paid activities nursery higher internet famrel freetime  \
0          2   ...       1          1       0      0        1      4        3
1          2   ...       1          1       1      0        0      5        3
2          2   ...       0          1       0      0        0      4        3
3          3   ...       0          0       0      0        0      3        2
4          2   ...       0          1       0      0        1      4        3

  health  absences  Scores
0      3         6      17
1      3         4      16
2      3        10      25
3      5         2      44
4      5         4      26

[5 rows x 23 columns]

In [94]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(file_new,file_new['Scores'], random_state = 0)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)

In [119]:
file_new.head()

,S/N,Gender,Age,Location,famsize,Pstatus,Medu,Fedu,traveltime,studytime,...,paid,activities,nursery,higher,internet,famrel,freetime,health,absences,Scores
0,AB1,0,13,0,1,1,4,4,2,2,...,1,1,0,0,1,4,3,3,6,17
1,AB2,0,12,0,1,0,1,1,1,2,...,1,1,1,0,0,5,3,3,4,16
2,AB3,0,10,0,0,0,1,1,1,2,...,0,1,0,0,0,4,3,3,10,25
3,AB4,0,10,0,1,0,4,2,1,3,...,0,0,0,0,0,3,2,5,2,44
4,AB5,0,11,0,1,0,3,3,1,2,...,0,1,0,0,1,4,3,5,4,26

In [141]:
count = 1

    
for i in range(len(file_new['S/N'])):
    file_new['S/N'][i] = count
    count += 1

C:\Users\ACER\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\ACER\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2881: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

In [142]:
file_new.head()

,S/N,Gender,Age,Location,famsize,Pstatus,Medu,Fedu,traveltime,studytime,...,40,41,42,43,44,45,46,47,48,49
0,1,0,13,0,1,1,4,4,2,2,...,41,42,43,44,45,46,47,48,49,50
1,2,0,12,0,1,0,1,1,1,2,...,41,42,43,44,45,46,47,48,49,50
2,3,0,10,0,0,0,1,1,1,2,...,41,42,43,44,45,46,47,48,49,50
3,4,0,10,0,1,0,4,2,1,3,...,41,42,43,44,45,46,47,48,49,50
4,5,0,11,0,1,0,3,3,1,2,...,41,42,43,44,45,46,47,48,49,50

In [143]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(file_new,file_new['Scores'], random_state = 0)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)

In [144]:
knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [145]:
y_pred = knn.predict_proba(X_test)

In [154]:
y_pre =knn.predict(X_test)

In [156]:
knn.score(X_test, Y_test)

0.0

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as sk

In [2]:
from sklearn.svm import SVC

In [3]:
help (plt.legend)

Help on function legend in module matplotlib.pyplot:

legend(*args, **kwargs)
    Places a legend on the axes.

    To make a legend for lines which already exist on the axes
    (via plot for instance), simply call this function with an iterable
    of strings, one for each legend item. For example::

        ax.plot([1, 2, 3])
        ax.legend(['A simple line'])

    However, in order to keep the "label" and the legend element
    instance together, it is preferable to specify the label either at
    artist creation, or by calling the
    :meth:`~matplotlib.artist.Artist.set_label` method on the artist::

        line, = ax.plot([1, 2, 3], label='Inline label')
        # Overwrite the label by calling the method.
        line.set_label('Label via method')
        ax.legend()

    Specific lines can be excluded from the automatic legend element
    selection by defining a label starting with an underscore.
    This is default for all artists, so calling :meth:`legend` without
    any arguments and without setting the labels manually will result in
    no legend being drawn.

    For full control of which artists have a legend entry, it is possible
    to pass an iterable of legend artists followed by an iterable of
    legend labels respectively::

       legend((line1, line2, line3), ('label1', 'label2', 'label3'))

    Parameters
    ----------
    loc : int or string or pair of floats, default: 'upper right'
        The location of the legend. Possible codes are:

            ===============   =============
            Location String   Location Code
            ===============   =============
            'best'            0
            'upper right'     1
            'upper left'      2
            'lower left'      3
            'lower right'     4
            'right'           5
            'center left'     6
            'center right'    7
            'lower center'    8
            'upper center'    9
            'center'          10
            ===============   =============


        Alternatively can be a 2-tuple giving ``x, y`` of the lower-left
        corner of the legend in axes coordinates (in which case
        ``bbox_to_anchor`` will be ignored).

    bbox_to_anchor : :class:`matplotlib.transforms.BboxBase` instance or tuple of floats
        Specify any arbitrary location for the legend in `bbox_transform`
        coordinates (default Axes coordinates).

        For example, to put the legend's upper right hand corner in the
        center of the axes the following keywords can be used::

           loc='upper right', bbox_to_anchor=(0.5, 0.5)

    ncol : integer
        The number of columns that the legend has. Default is 1.

    prop : None or :class:`matplotlib.font_manager.FontProperties` or dict
        The font properties of the legend. If None (default), the current
        :data:`matplotlib.rcParams` will be used.

    fontsize : int or float or {'xx-small', 'x-small', 'small', 'medium', 'large', 'x-large', 'xx-large'}
        Controls the font size of the legend. If the value is numeric the
        size will be the absolute font size in points. String values are
        relative to the current default font size. This argument is only
        used if `prop` is not specified.

    numpoints : None or int
        The number of marker points in the legend when creating a legend
        entry for a line/:class:`matplotlib.lines.Line2D`.
        Default is ``None`` which will take the value from the
        ``legend.numpoints`` :data:`rcParam<matplotlib.rcParams>`.

    scatterpoints : None or int
        The number of marker points in the legend when creating a legend
        entry for a scatter plot/
        :class:`matplotlib.collections.PathCollection`.
        Default is ``None`` which will take the value from the
        ``legend.scatterpoints`` :data:`rcParam<matplotlib.rcParams>`.

    scatteryoffsets : iterable of floats
        The vertical offset (relative to the font size) for the markers
        created for a scatter plot legend entry. 0.0 is at the base the
        legend text, and 1.0 is at the top. To draw all markers at the
        same height, set to ``[0.5]``. Default ``[0.375, 0.5, 0.3125]``.

    markerscale : None or int or float
        The relative size of legend markers compared with the originally
        drawn ones. Default is ``None`` which will take the value from
        the ``legend.markerscale`` :data:`rcParam <matplotlib.rcParams>`.

    markerfirst : bool
        if *True*, legend marker is placed to the left of the legend label
        if *False*, legend marker is placed to the right of the legend
        label

    frameon : None or bool
        Control whether the legend should be drawn on a patch (frame).
        Default is ``None`` which will take the value from the
        ``legend.frameon`` :data:`rcParam<matplotlib.rcParams>`.

    fancybox : None or bool
        Control whether round edges should be enabled around
        the :class:`~matplotlib.patches.FancyBboxPatch` which
        makes up the legend's background.
        Default is ``None`` which will take the value from the
        ``legend.fancybox`` :data:`rcParam<matplotlib.rcParams>`.

    shadow : None or bool
        Control whether to draw a shadow behind the legend.
        Default is ``None`` which will take the value from the
        ``legend.shadow`` :data:`rcParam<matplotlib.rcParams>`.

    framealpha : None or float
        Control the alpha transparency of the legend's background.
        Default is ``None`` which will take the value from the
        ``legend.framealpha`` :data:`rcParam<matplotlib.rcParams>`.

    facecolor : None or "inherit" or a color spec
        Control the legend's background color.
        Default is ``None`` which will take the value from the
        ``legend.facecolor`` :data:`rcParam<matplotlib.rcParams>`.
        If ``"inherit"``, it will take the ``axes.facecolor``
        :data:`rcParam<matplotlib.rcParams>`.

    edgecolor : None or "inherit" or a color spec
        Control the legend's background patch edge color.
        Default is ``None`` which will take the value from the
        ``legend.edgecolor`` :data:`rcParam<matplotlib.rcParams>`.
        If ``"inherit"``, it will take the ``axes.edgecolor``
        :data:`rcParam<matplotlib.rcParams>`.

    mode : {"expand", None}
        If `mode` is set to ``"expand"`` the legend will be horizontally
        expanded to fill the axes area (or `bbox_to_anchor` if defines
        the legend's size).

    bbox_transform : None or :class:`matplotlib.transforms.Transform`
        The transform for the bounding box (`bbox_to_anchor`). For a value
        of ``None`` (default) the Axes'
        :data:`~matplotlib.axes.Axes.transAxes` transform will be used.

    title : str or None
        The legend's title. Default is no title (``None``).

    borderpad : float or None
        The fractional whitespace inside the legend border.
        Measured in font-size units.
        Default is ``None`` which will take the value from the
        ``legend.borderpad`` :data:`rcParam<matplotlib.rcParams>`.

    labelspacing : float or None
        The vertical space between the legend entries.
        Measured in font-size units.
        Default is ``None`` which will take the value from the
        ``legend.labelspacing`` :data:`rcParam<matplotlib.rcParams>`.

    handlelength : float or None
        The length of the legend handles.
        Measured in font-size units.
        Default is ``None`` which will take the value from the
        ``legend.handlelength`` :data:`rcParam<matplotlib.rcParams>`.

    handletextpad : float or None
        The pad between the legend handle and text.
        Measured in font-size units.
        Default is ``None`` which will take the value from the
        ``legend.handletextpad`` :data:`rcParam<matplotlib.rcParams>`.

    borderaxespad : float or None
        The pad between the axes and legend border.
        Measured in font-size units.
        Default is ``None`` which will take the value from the
        ``legend.borderaxespad`` :data:`rcParam<matplotlib.rcParams>`.

    columnspacing : float or None
        The spacing between columns.
        Measured in font-size units.
        Default is ``None`` which will take the value from the
        ``legend.columnspacing`` :data:`rcParam<matplotlib.rcParams>`.

    handler_map : dict or None
        The custom dictionary mapping instances or types to a legend
        handler. This `handler_map` updates the default handler map
        found at :func:`matplotlib.legend.Legend.get_legend_handler_map`.

    Notes
    -----

    Not all kinds of artist are supported by the legend command.
    See :ref:`plotting-guide-legend` for details.

    Examples
    --------

    .. plot:: mpl_examples/api/legend_demo.py